
spring:
  application:

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${user:adel}
    password: ${DB_PASS:passer123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:jwt}
  flyway:
    enabled: false



server:
  port: 8080

